### ISSUE TITLE
UX fury needs to be allowed to select two handed weapons

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#28]
Makhno: 2H weapons are "restricted" for Fury, but 2H Fury is still possible in BC

**Comment by Bonkeybee** [comment]
Full review of item restrictions and how they are applied is likely still required.

**Comment by Elite747** [comment]
This falls under an edge-case category of restrictions that go beyond the standard restrictions based on role (tank, heal, melee, ranged, and caster) and go into the exact talent points chosen within a spec.

If I recall correctly, all of these edge cases are:
1. One-hand vs. two-hand for warriors and enhancement shaman
2. Weapon type for rogues (sword, dagger, mace, fist)
3. School-of-magic specific spellpower items. (eg. +fire damage, +shadow damage)

Of all of these cases, the first one is the only one I've implemented special rules for. In the case of enhancement shaman, it's categorized as [manual review](https://github.com/Elite747/ValhallaLootList/blob/master/src/SeedAndMigrate/ItemDeterminer/Rules/ManualReview/EnhancementShamanShouldUseDualWieldRule.cs). This is because, while shaman can use two-handed maces and axes, their talent tree is very clearly designed for dual-wielding and I've heard nothing about 2h being viable for raiding. For warriors, they have two melee dps specs. One has dual-wield specialization, and the other two-handed specialization. With that, I've split the warrior dps role into each individual spec. It's the only class that is like that. All other classes that have two specs that fill the same role are combined during loot list creation. The only difference when creating a list using arms or fury as a spec is the 1h vs 2h rules. The spirit of this rule is to limit your weapon options to a single category. While it may be true that fury *can* use 2h, allowing them to select 2h weapons would go against the purpose of splitting them, and should only be approved on a case-by-case basis. The rules that support this are [here for arms](https://github.com/Elite747/ValhallaLootList/blob/master/src/SeedAndMigrate/ItemDeterminer/Rules/Disallowed/ArmsWarriorsShouldOnlyUseTwoHandersRule.cs) and [here for fury](https://github.com/Elite747/ValhallaLootList/blob/master/src/SeedAndMigrate/ItemDeterminer/Rules/Disallowed/FuryWarriorsShouldOnlyUseOneHandersRule.cs). I can move these rules to manual review instead of restricted if that would solve this issue, but the point of putting it as restricted is to limit people to going after only one weapon type.

**Comment by Bonkeybee** [comment]
After reading your explanation I agree with you and would recommend to
leave the restrictions as is
