### ISSUE TITLE
Add functionality for a loot list "sandbox" so people can create test/sample lists independent of their character

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#90]

**Comment by Elite747** [comment]
Sandboxes would be a very complex addition with a limited value.

Since any changes to a list entry requires a full client>server interaction to verify the validity of the change, the sandbox lists would either have to be stored server-side alongside real lists, or an entire rewrite of the logic would have to be made so that validation can occur both on the client and on the server.

For someone who really wants to play around with a test list, I'd rather just suggest using the dev site instead.
